### ISSUE TITLE
Logo / Website design

### ISSUE THREAD

**Issue by egoist** [upash/peco#7]
I made a temporary logo:

![image](https://user-images.githubusercontent.com/8784712/39350489-e880ca80-4a30-11e8-9db7-5ea0f7e1d06e.png)

Doesn't look very good but I'll just it for now..

If you're a designer, we can use your help! And it's very much appreciated. 😄

**Comment by shakdaniel** [comment]
what’s the meaning behind peco? give me some context, i’ll help.

**Comment by egoist** [comment]
@shakdaniel it's the name of a game in an anime 😅 not really related to this project

**Comment by gustojs** [comment]
And here I thought it's a character from Ping Pong the Animation.

**Comment by egoist** [comment]
@gustojs that's new to me 😂

**Comment by filipbasara** [comment]
How about something along the lines of this?
![peco_logo_proposal](https://user-images.githubusercontent.com/2316510/41499872-9d5c723c-7188-11e8-8d9b-f8a529f7e5e2.jpg)

**Comment by filipbasara** [comment]
Paging @egoist 
Feedback would be appreciated!

**Comment by egoist** [comment]
the `p` icon alone looks not bad, the text on the right doesn't fit very well.

**Comment by f3ltron** [comment]
give us a link to the anime game you spoke :)

**Comment by egoist** [comment]
thanks for the interests, this is now moved to https://github.com/egoist/saber/issues/22
